definitions:
  create_segment.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  create_user.Request:
    properties:
      addedSeg:
        items:
          $ref: '#/definitions/create_user.SegmentWithTime'
        type: array
      removeSeg:
        items:
          type: string
        type: array
    type: object
  create_user.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  create_user.SegmentWithTime:
    properties:
      segment:
        type: string
      time:
        type: string
    type: object
  delete_segment.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  delete_user.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  segment_list.Response:
    properties:
      error:
        type: string
      segmentList:
        items:
          type: string
        type: array
      status:
        type: string
    type: object
  segment_users.Response:
    properties:
      error:
        type: string
      status:
        type: string
      userList:
        items:
          type: string
        type: array
    type: object
  user_list.Response:
    properties:
      error:
        type: string
      status:
        type: string
      userList:
        items:
          type: string
        type: array
    type: object
  user_log.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  user_segments.Response:
    properties:
      error:
        type: string
      segments:
        items:
          type: string
        type: array
      status:
        type: string
    type: object
host: localhost:8002
info:
  contact:
    email: feodor200@mail.ru
    name: GhostikGH
    url: https://t.me/GhostikGH
  description: Segmentation for A_B tests
  title: Avito Intership (Backend)
  version: "1.0"
paths:
  /log/{user_id}:
    get:
      description: Возвращает CSV файл для выбранного пользователя
      operationId: user-log
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_log.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/user_log.Response'
      summary: Лог пользователя
      tags:
      - Log
  /segment:
    get:
      consumes:
      - application/json
      description: Возвращает список всех зарегистрированных пользователей
      operationId: segment-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/segment_list.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/segment_list.Response'
      summary: Получения списка всех сегментов
      tags:
      - Segment
  /segment/{segment}:
    delete:
      consumes:
      - application/json
      description: Удаляет сегмент, соответственно и всех пользователей из него
      operationId: segment-deletion
      parameters:
      - description: segment name
        in: path
        name: segment
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delete_segment.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/delete_segment.Response'
      summary: Удаление сегмента
      tags:
      - Segment
    get:
      consumes:
      - application/json
      description: Получение всех пользователей в данном сегменте
      operationId: segment-user-list
      parameters:
      - description: segment name
        in: path
        name: segment
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/segment_users.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/segment_users.Response'
      summary: Все пользователи сегмента
      tags:
      - Segment
  /segment/{segment}/{percentage}:
    post:
      consumes:
      - application/json
      description: Создает сегмент, необязательное поле указывает на то сколько процентов
        (float от 0 до 100) от зарегистрированных пользователей попадет в выборка
      operationId: segment-creation
      parameters:
      - description: segment name
        in: path
        name: segment
        required: true
        type: string
      - description: percentage
        in: path
        name: percentage
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/create_segment.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/create_segment.Response'
      summary: Создание сегмента
      tags:
      - Segment
  /user:
    get:
      consumes:
      - application/json
      description: Возвращает список всех зарегистрированных пользователей
      operationId: user-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_list.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/user_list.Response'
      summary: Список всех пользователей
      tags:
      - User
  /user/{user_id}:
    delete:
      consumes:
      - application/json
      description: Удаление пользователя, удаляются все записи
      operationId: user-deletion
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delete_user.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/delete_user.Response'
      summary: Удаление пользователя
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Получение всех сегментов данного пользователя
      operationId: user-segment-list
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_segments.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/user_segments.Response'
      summary: Сегменты пользователя
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Изменяет состояние сегментов у пользователя, если пользователя
        нет, то он созадется. Также доступен timestamp в формате YYYY MM DD HH:MM:SS+00
      operationId: create-user
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: integer
      - description: user update data
        in: body
        name: input
        schema:
          $ref: '#/definitions/create_user.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/create_user.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/create_user.Response'
      summary: Изменение сегментов у одного пользователя
      tags:
      - User
swagger: "2.0"
